function [ N, dNdx, dNdy, detJac ] = T6_Element( X,Y,xis,eta )
N = [(1 - xis - eta).*(1 - 2*xis - 2*eta),...
    4*xis.*(1 - xis - eta),...
    xis.*(2*xis - 1),...
    4*xis.*eta,...
    eta.*(2*eta - 1),...
    4*eta.*(1 - xis - eta)];
% x = N(:,1)*X(1) + N(:,2)*X(2) + N(:,3)*X(3) + N(:,4)*X(4) + N(:,5)*X(5) + N(:,6)*X(6);
% y = N(:,1)*Y(1) + N(:,2)*Y(2) + N(:,3)*Y(3) + N(:,4)*Y(4) + N(:,5)*Y(5) + N(:,6)*Y(6);
dNdxis = [4*eta + 4*xis - 3,...
    4 - 8*xis - 4*eta,...
    4*xis - 1,...
    4*eta,...
    0*xis,...
    -4*eta];
dNdeta = [4*eta + 4*xis - 3,...
    -4*xis,...
    0*xis,...
    4*xis,...
    4*eta - 1,...
    4 - 4*xis - 8*eta];

dxdxis = dNdxis*X;
dxdeta = dNdeta*X;
dydxis = dNdxis*Y;
dydeta = dNdeta*Y;

detJac = dxdxis.*dydeta-dxdeta.*dydxis;
dxisdx =  dydeta./detJac;
dxisdy = -dxdeta./detJac;
detadx = -dydxis./detJac;
detady =  dxdxis./detJac;
for i = 1:length(dxisdx)
    dNdx(i,:) = dNdxis(i,:)*dxisdx(i) + dNdeta(i,:)*detadx(i);
    dNdy(i,:) = dNdxis(i,:)*dxisdy(i) + dNdeta(i,:)*detady(i);
end
